Anagram
rybmks/rust-exercism pull request #7
Opened 2024-08-09 16:00 UTC by rybmks

2024-08-10 15:36 UTC, YBoy-git requested changes

2024-08-10 15:36 UTC, YBoy-git commented on src/lib.rs
> +mod reverse_string;
You are not exposing the internal functions to the lib user. You must specify `pub mod` to allow users to refer to the module and its child elements.

And then remove `allow(dead_code)` (it shouldn't print any warnings as the functions are going to be counted as public)

2024-08-10 15:36 UTC, YBoy-git commented on src/anagram.rs
> +}
Nice solution.
For me, the most obvious one here was to sort the strings and then compare them, but the solution has a bad time complexity.
As an exercise, write a quick time and space complexity analysis for your solution (as a response to this comment).

2024-08-14 18:20 UTC, rybmks commented on src/anagram.rs
> +}
O(n * k), where n - amount of strings, k - chars amount.

2024-08-15 09:10 UTC, YBoy-git commented on src/anagram.rs
> +}
Which complexity is this one? Time or space complexity? Are they the same?

2024-09-03 17:24 UTC, rybmks commented on src/anagram.rs
> +}
O(n*k) is time complexity. Space complexity is O((m + k )* n), k is amount of unique chars in word, m is word length (when we are creating a lowercase string), n is amount of strings

2024-09-04 18:21 UTC, YBoy-git approved these changes
Nice work on space complexity

2024-09-04 18:21 UTC, merged